### ISSUE TITLE
Comparison to existing installers

### ISSUE THREAD

**Issue by pyfisch** [kgizdov/arch-installer#4]
There are at least two actively maintained installers for Arch Linux:

* [Anarchy Installer](https://anarchyinstaller.org/)
* [Manjaro Architect](https://gitlab.manjaro.org/applications/manjaro-architect)

While of course Manjaro isn't Arch Linux I would expect the installer to rather similar and assume it can be tweaked to work with Arch.

What sets this proposed Arch installer apart from these two existing programs?

**Comment by RandoNandoz** [comment]
What about EndeavourOS & Garuda Linux's installers?

**Comment by shibumi** [comment]
Hi,

IIRC Anarchy Installer is TUI-only. We actually wanted to have a GUI installer for Arch Linux with full mouse support. Something that looks easy to use and inviting to new users.

Manjaro Architect is a no-go for us, because it's manjaro :D 

About EndeavourOS and Garuda Installer. No idea, I did not take a look on them.

EDIT: EndeavourOS is Calamares (same like Manjaro). Calamares had some major pain points for us.

**Comment by RandoNandoz** [comment]
Garuda is calamares as well.

**Comment by RandoNandoz** [comment]
What about Clear Linux's installer? https://github.com/clearlinux/clr-installer

**Comment by shibumi** [comment]
@RandoNandoz  no idea how difficult this would be to adjust for Arch Linux.

**Comment by Torxed** [comment]
I'll just mention that [archinstall](https://github.com/Torxed/archinstall) was added today to the [official iso](https://archlinux.org/news/installation-medium-with-installer/) as an optional installer. Full disclaimer is that I'm the maintainer and it does have a not at all up to date [GUI](https://github.com/Torxed/archinstall_gui) as well with very poorly written HTML/CSS.

But I do welcome any feedback, comparisons and ideas :)

**Comment by kgizdov** [comment]
this project will be archived until further notice
